### ISSUE TITLE
hook ios crash

### ISSUE THREAD

**Issue by greadwallmem** [jmpews/Dobby#101]
i hook an app for sub_xxxx crash 。     error msg:Received event: com.apple.stability.crash {"appVersion":"2.8.5","bundleID":"com.test","exceptionCodes":"0x0000000000000001, 0x0000000000000000","logwritten":0,"process":"wework","terminationReasonExceptionCode":"0x2","terminationReasonNamespace":"CODESIGNING"}

**Comment by greadwallmem** [comment]
what's happen?

**Comment by jmpews** [comment]
iOS Version ?

**Comment by greadwallmem** [comment]
ios 13.6.1   use xcode lldb debug don't crash . but direct run crash

**Comment by jmpews** [comment]
You need jailbreak!!!

**Comment by greadwallmem** [comment]
dobby not support ios non-jailbreak？？？
