### ISSUE TITLE
ios 13 crash 。how to fix？？？？？？

### ISSUE THREAD

**Issue by greadwallmem** [jmpews/Dobby#102]
ios 13 crash 。how to fix？？？？？？

**Comment by jmpews** [comment]
dobby works under jailbreak like cyida substrate, so you need jailbreaked iphone.

**Comment by greadwallmem** [comment]
cydia substrate can hook in none-jailbreak

**Comment by jmpews** [comment]
it's objective-c method swizzling, but inlinehook NOT!
