### ISSUE TITLE
iphone6s下会闪退，Binary is improperly signed

### ISSUE THREAD

**Issue by stoneJu** [jmpews/Dobby#104]
设备：iphone6s
系统：12.1.4
越狱：unc0ver
在调用DobbyInstrument的时候闪退，日志报Binary is improperly signed
同样代码在iphone6的12系统下，unc0ver越狱使用正常

**Comment by stoneJu** [comment]
iphone6直接使用ldid -S 签过就正常，iphone6s使用ldid -S 或者使用codesign -f -s签一个developer证书也同样报错

**Comment by jmpews** [comment]
签名问题... 可能需要你自己去解决... 可以把 Dobby 编译成 static library
