### ISSUE TITLE
fd not closed

### ISSUE THREAD

**Issue by kotori2** [jmpews/Dobby#108]
https://github.com/jmpews/Dobby/blob/ef23b30985c1e632c33c1053e5b456ca979d4151/builtin-plugin/SymbolResolver/elf/dobby_symbol_resolver.cc#L23-L50

**Comment by kotori2** [comment]
also this one
https://github.com/jmpews/Dobby/blob/6cedb0b8f0b52f4742d57d39e1d9106fc696a692/source/UserMode/PlatformUtil/Linux/ProcesssRuntimeUtility.cc#L27

**Comment by kotori2** [comment]
and this
https://github.com/jmpews/Dobby/blob/6cedb0b8f0b52f4742d57d39e1d9106fc696a692/source/UserMode/PlatformUtil/Linux/ProcesssRuntimeUtility.cc#L101

**Comment by jmpews** [comment]
thx 😀

i'll fix it soon.
