### ISSUE TITLE
Can't hook art::gc::Heap::PreZygoteFork on Android 11 with ARM

### ISSUE THREAD

**Issue by kotori2** [jmpews/Dobby#109]
In [my own fork of EdXposed](https://github.com/kotori2/EdXposed/tree/android_r), there [is a hook for `art::gc::Heap::PreZygoteFork`](https://github.com/kotori2/EdXposed/blob/6a660318ba223e538b678fbb77a0ac932ba47da2/edxp-core/src/main/cpp/main/include/art/runtime/gc/heap.h#L42). It works. fine on ARM64 but failed on ARM. 

Stack trace: 

![telegram-cloud-photo-size-5-6134389153815702320-y](https://user-images.githubusercontent.com/17663689/98280322-3229e180-1fd6-11eb-920d-4416ba1b0d4a.jpg)
![telegram-cloud-photo-size-5-6134389153815702323-y](https://user-images.githubusercontent.com/17663689/98280529-803ee500-1fd6-11eb-8ef8-7accb73229d9.jpg)

Disassembled function (on Pixel 4 XL, RP1A.201005.004, `/apex/com.android.art/lib/libart.so`):
![telegram-cloud-photo-size-5-6134389153815702322-y](https://user-images.githubusercontent.com/17663689/98280455-66050700-1fd6-11eb-8349-91a3fea05d2b.jpg)

It seems SP register was messed up here. 
Also the hook fails at System UI and the system crashes, so I don't have time to attach a debugger.
Any advice on how to debug it here?

**Comment by jmpews** [comment]
hi, i'll  test it today.

**Comment by jmpews** [comment]
@kotori2 Any contact? wechat?

**Comment by kotori2** [comment]
~~Email sent to the address on your profile page~~

**Comment by kotori2** [comment]
fixed https://github.com/jmpews/Dobby/commit/b3b3f8160f84c1e94d7a66c36488d63ef5f5d450
