### ISSUE TITLE
[bug] Fails to build on latest macOS setup (Big Sur) 

### ISSUE THREAD

**Issue by ko1o** [jmpews/Dobby#117]
ld: in /var/folders/xx/b4bgcx_1393fdwdnddgzkqmc0000gn/T/CocoaPods-Lint-20201210-38015-ancczl-CocoaHotReload/Pods/CocoaHotReload/CocoaHotReload/ThirdUitlities/Dobby/lib/libdobby.a(CpuFeature.cc.o), building for iOS Simulator, but linking in object file built for iOS, file '/var/folders/xx/b4bgcx_1393fdwdnddgzkqmc0000gn/T/CocoaPods-Lint-20201210-38015-ancczl-CocoaHotReload/Pods/CocoaHotReload/CocoaHotReload/ThirdUitlities/Dobby/lib/libdobby.a' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

https://github.com/leetal/ios-cmake/issues/88

**Comment by jmpews** [comment]
solved ？
