### ISSUE TITLE
DobbyHook出现 Crash在iPhone 模拟器 x86_64 架构上

### ISSUE THREAD

**Issue by ko1o** [jmpews/Dobby#118]
![image](https://user-images.githubusercontent.com/13819507/102206591-d83b0680-3f07-11eb-8c55-1c03940a60b6.png)

CocoaHotReloadExample-CocoaPods`GenerateNormalTrampolineBuffer:
    0x10579e9b0 <+0>:   pushq  %rbp
    0x10579e9b1 <+1>:   movq   %rsp, %rbp
    0x10579e9b4 <+4>:   pushq  %r15
    0x10579e9b6 <+6>:   pushq  %r14
    0x10579e9b8 <+8>:   pushq  %r12
    0x10579e9ba <+10>:  pushq  %rbx
    0x10579e9bb <+11>:  subq   $0x30, %rsp
    0x10579e9bf <+15>:  movq   %rsi, %r15
    0x10579e9c2 <+18>:  movq   %rdi, %r12
    0x10579e9c5 <+21>:  leaq   -0x40(%rbp), %r14
    0x10579e9c9 <+25>:  movq   %r14, %rdi
    0x10579e9cc <+28>:  movq   %r12, %rsi
    0x10579e9cf <+31>:  callq  0x10579d130               ; zz::AssemblerBase::AssemblerBase(void*)
    0x10579e9d4 <+36>:  leaq   0x37dc5(%rip), %rax       ; vtable for zz::x64::Assembler + 16
    0x10579e9db <+43>:  movq   %rax, -0x40(%rbp)
    0x10579e9df <+47>:  movl   $0x20, %edi
    0x10579e9e4 <+52>:  callq  0x1057caf6e               ; symbol stub for: operator new(unsigned long)
    0x10579e9e9 <+57>:  movq   %rax, %rbx
    0x10579e9ec <+60>:  leaq   0x3a8b5(%rip), %rax       ; vtable for LiteMutableBuffer
    0x10579e9f3 <+67>:  leaq   0x10(%rax), %rcx
    0x10579e9f7 <+71>:  movq   %rcx, (%rbx)
    0x10579e9fa <+74>:  movq   %rbx, %rdi
    0x10579e9fd <+77>:  movl   $0x20, %esi
    0x10579ea02 <+82>:  callq  *0x20(%rax)
    0x10579ea05 <+85>:  leaq   0x37db4(%rip), %rax       ; vtable for CodeBuffer + 16
    0x10579ea0c <+92>:  movq   %rax, (%rbx)
    0x10579ea0f <+95>:  movq   %rbx, -0x38(%rbp)
    0x10579ea13 <+99>:  leaq   0x37d66(%rip), %rax       ; vtable for zz::x64::TurboAssembler + 16
    0x10579ea1a <+106>: movq   %rax, -0x40(%rbp)
    0x10579ea1e <+110>: movq   $0x0, -0x28(%rbp)
    0x10579ea26 <+118>: movl   $0x80000000, %esi         ; imm = 0x80000000 
    0x10579ea2b <+123>: movq   %r12, %rdi
    0x10579ea2e <+126>: movl   $0x8, %edx
    0x10579ea33 <+131>: callq  0x1057a1430               ; NearMemoryArena::AllocateDataChunk(unsigned long, unsigned long, int)
    0x10579ea38 <+136>: testq  %rax, %rax
    0x10579ea3b <+139>: je     0x10579ea42               ; <+146>
    0x10579ea3d <+141>: movq   (%rax), %rsi
    0x10579ea40 <+144>: jmp    0x10579ea44               ; <+148>
    0x10579ea42 <+146>: xorl   %esi, %esi
->  0x10579ea44 <+148>: movq   %r15, (%rsi)
    0x10579ea47 <+151>: movq   %r14, -0x48(%rbp)
    0x10579ea4b <+155>: leaq   -0x48(%rbp), %rdi
    0x10579ea4f <+159>: callq  0x10579d1e0               ; zz::x64::CodeGen::JmpNearIndirect(unsigned long long)
    0x10579ea54 <+164>: leaq   -0x40(%rbp), %rdi
    0x10579ea58 <+168>: callq  0x10579d190               ; zz::AssemblerBase::GetCodeBuffer()
    0x10579ea5d <+173>: movq   (%rax), %rcx
    0x10579ea60 <+176>: movq   %rax, %rdi
    0x10579ea63 <+179>: callq  *0x40(%rcx)
    0x10579ea66 <+182>: movq   %rax, %rbx
    0x10579ea69 <+185>: leaq   -0x40(%rbp), %rdi
    0x10579ea6d <+189>: callq  0x10579daf0               ; zz::x64::TurboAssembler::~TurboAssembler()
    0x10579ea72 <+194>: movq   %rbx, %rax
    0x10579ea75 <+197>: addq   $0x30, %rsp
    0x10579ea79 <+201>: popq   %rbx
    0x10579ea7a <+202>: popq   %r12
    0x10579ea7c <+204>: popq   %r14
    0x10579ea7e <+206>: popq   %r15
    0x10579ea80 <+208>: popq   %rbp
    0x10579ea81 <+209>: retq   
    0x10579ea82 <+210>: jmp    0x10579eaa1               ; <+241>
    0x10579ea84 <+212>: jmp    0x10579eaa1               ; <+241>
    0x10579ea86 <+214>: movq   %rax, %r14
    0x10579ea89 <+217>: movq   %rbx, %rdi
    0x10579ea8c <+220>: callq  0x1057caf68               ; symbol stub for: operator delete(void*)
    0x10579ea91 <+225>: jmp    0x10579ea96               ; <+230>
    0x10579ea93 <+227>: movq   %rax, %r14
    0x10579ea96 <+230>: leaq   -0x40(%rbp), %rdi
    0x10579ea9a <+234>: callq  0x10579d150               ; zz::AssemblerBase::~AssemblerBase()
    0x10579ea9f <+239>: jmp    0x10579eaad               ; <+253>
    0x10579eaa1 <+241>: movq   %rax, %r14
    0x10579eaa4 <+244>: leaq   -0x40(%rbp), %rdi
    0x10579eaa8 <+248>: callq  0x10579daf0               ; zz::x64::TurboAssembler::~TurboAssembler()
    0x10579eaad <+253>: movq   %r14, %rdi
    0x10579eab0 <+256>: callq  0x1057caf50               ; symbol stub for: _Unwind_Resume
    0x10579eab5 <+261>: ud2    
    0x10579eab7 <+263>: nop    
    0x10579eab8 <+264>: nop    
    0x10579eab9 <+265>: nop    
    0x10579eaba <+266>: nop    
    0x10579eabb <+267>: nop    
    0x10579eabc <+268>: nop    
    0x10579eabd <+269>: nop    
    0x10579eabe <+270>: nop    
    0x10579eabf <+271>: nop

**Comment by ko1o** [comment]
真机arm64 没有这个问题 只有模拟器x86_64架构有这问题

**Comment by jmpews** [comment]
是用的最新的 commit 嘛？

**Comment by ko1o** [comment]
上周四的最新代码 symbol 是c函数 名字是 "cFunction" 源码如下
```c
void cFunction(void) {
    printf("c2333 functionxxx\n");
}
```

**Comment by ko1o** [comment]
我生成.a的脚本如下：
```shell
cd `dirname $0`
CURRENT_DIR=$(pwd)

git clone https://github.com/jmpews/Dobby.git

DOBBY_MASTER_DIR=$CURRENT_DIR/Dobby
cd $DOBBY_MASTER_DIR

rm -rf build_for_ios || true
mkdir build_for_ios
PRODUCT_DIR=$DOBBY_MASTER_DIR/build_for_ios

cd $PRODUCT_DIR
# build for armv7
mkdir $PRODUCT_DIR/build_for_armv7 && cd $PRODUCT_DIR/build_for_armv7
echo `pwd`
cmake ../.. \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DPLATFORM=OS -DARCHS="armv7" -DCMAKE_SYSTEM_PROCESSOR=arm \
-DENABLE_BITCODE=1 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 -DCMAKE_BUILD_TYPE=Release -DDOBBY_DEBUG=OFF -DDOBBY_GENERATE_SHARED=OFF -DDarwin.GenerateFramework=OFF

make -j4

# build for arm64
mkdir $PRODUCT_DIR/build_for_arm64 && cd $PRODUCT_DIR/build_for_arm64
cmake ../../ \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DPLATFORM=OS64 -DARCHS="arm64" -DCMAKE_SYSTEM_PROCESSOR=arm64 \
-DENABLE_BITCODE=1 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 -DCMAKE_BUILD_TYPE=Release -DDOBBY_DEBUG=OFF -DDOBBY_GENERATE_SHARED=OFF -DDarwin.GenerateFramework=OFF

make -j4

# build for i386
mkdir $PRODUCT_DIR/build_for_i386 && cd $PRODUCT_DIR/build_for_i386
cmake ../../ \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DPLATFORM=SIMULATOR -DARCHS="i386" -DCMAKE_SYSTEM_PROCESSOR=X86 \
-DENABLE_BITCODE=1 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 -DCMAKE_BUILD_TYPE=Release -DDOBBY_DEBUG=OFF -DDOBBY_GENERATE_SHARED=OFF -DDarwin.GenerateFramework=OFF

make -j4

# build for x86_64
mkdir $PRODUCT_DIR/build_for_x86_64 && cd $PRODUCT_DIR/build_for_x86_64
cmake ../../ \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DPLATFORM=SIMULATOR64 -DARCHS="x86_64" -DCMAKE_SYSTEM_PROCESSOR=X86_64 \
-DENABLE_BITCODE=1 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 -DCMAKE_BUILD_TYPE=Release -DDOBBY_DEBUG=OFF -DDOBBY_GENERATE_SHARED=OFF -DDarwin.GenerateFramework=OFF

make -j4

LIB_DIR=$CURRENT_DIR/lib

rm -rf $LIB_DIR || true
mkdir $LIB_DIR

# 生成static library
cp -R $DOBBY_MASTER_DIR/include $LIB_DIR/include
lipo -create $PRODUCT_DIR/build_for_i386/libdobby.a $PRODUCT_DIR/build_for_x86_64/libdobby.a $PRODUCT_DIR/build_for_armv7/libdobby.a $PRODUCT_DIR/build_for_arm64/libdobby.a -output $LIB_DIR/libdobby.a

# 移除dobby master
rm -rf $DOBBY_MASTER_DIR

open $CURRENT_DIR

```

**Comment by ko1o** [comment]
刚才更新了最新代码 重新生成.a 不会crash了 @jmpews

**Comment by wjiuxing** [comment]
@ko1o 你上面的脚本还能正常生成 .a 吗？我这里总是找不到符号

Undefined symbols for architecture x86_64:
  "_DobbyGlobalOffsetTableReplace", referenced from:
      ctor() in darwin_common_api.cc.o
  "_DobbyInstrument", referenced from:
      ctor() in darwin_common_api.cc.o
  "_DobbySymbolResolver", referenced from:
      ctor() in darwin_common_api.cc.o
  "_log_internal_impl", referenced from:
      common_handler(_RegisterContext*, _HookEntryInfo const*) in darwin_common_api.cc.o
      fake_pthread_create(_opaque_pthread_t**, _opaque_pthread_attr_t const*, void* (*)(void*), void*) in darwin_common_api.cc.o
      ctor() in darwin_common_api.cc.o
  "_log_set_level", referenced from:
      ctor() in darwin_common_api.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [example/darwin_example.app/darwin_example] Error 1
make[1]: *** [example/CMakeFiles/darwin_example.dir/all] Error 2

**Comment by ko1o** [comment]
> @ko1o 你上面的脚本还能正常生成 .a 吗？我这里总是找不到符号
> 
> ```shell
> Undefined symbols for architecture x86_64:
>   "_DobbyGlobalOffsetTableReplace", referenced from:
>       ctor() in darwin_common_api.cc.o
>   "_DobbyInstrument", referenced from:
>       ctor() in darwin_common_api.cc.o
>   "_DobbySymbolResolver", referenced from:
>       ctor() in darwin_common_api.cc.o
>   "_log_internal_impl", referenced from:
>       common_handler(_RegisterContext*, _HookEntryInfo const*) in darwin_common_api.cc.o
>       fake_pthread_create(_opaque_pthread_t**, _opaque_pthread_attr_t const*, void* (*)(void*), void*) in darwin_common_api.cc.o
>       ctor() in darwin_common_api.cc.o
>   "_log_set_level", referenced from:
>       ctor() in darwin_common_api.cc.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [example/darwin_example.app/darwin_example] Error 1
> make[1]: *** [example/CMakeFiles/darwin_example.dir/all] Error 2
> ```

我刚跑了一下是可以的啊

**Comment by ko1o** [comment]
@wjiuxing 试下我最新的脚本？
```shell
cd `dirname $0`
CURRENT_DIR=$(pwd)

git clone https://github.com/jmpews/Dobby.git

DOBBY_MASTER_DIR=$CURRENT_DIR/Dobby
cd $DOBBY_MASTER_DIR

rm -rf build_for_ios || true
mkdir build_for_ios
PRODUCT_DIR=$DOBBY_MASTER_DIR/build_for_ios

cd $PRODUCT_DIR
# build for armv7
mkdir $PRODUCT_DIR/build_for_armv7 && cd $PRODUCT_DIR/build_for_armv7
echo `pwd`
cmake ../.. \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DPLATFORM=OS -DARCHS="armv7" -DCMAKE_SYSTEM_PROCESSOR=arm \
-DENABLE_BITCODE=1 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 -DCMAKE_BUILD_TYPE=Release -DDOBBY_DEBUG=OFF -DDOBBY_GENERATE_SHARED=OFF -DGenerateDarwinFramework=OFF

make -j4

# build for arm64
mkdir $PRODUCT_DIR/build_for_arm64 && cd $PRODUCT_DIR/build_for_arm64
cmake ../../ \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DPLATFORM=OS64 -DARCHS="arm64" -DCMAKE_SYSTEM_PROCESSOR=arm64 \
-DENABLE_BITCODE=1 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 -DCMAKE_BUILD_TYPE=Release -DDOBBY_DEBUG=OFF -DDOBBY_GENERATE_SHARED=OFF -DGenerateDarwinFramework=OFF

make -j4

# build for i386
mkdir $PRODUCT_DIR/build_for_i386 && cd $PRODUCT_DIR/build_for_i386
cmake ../../ \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DPLATFORM=SIMULATOR -DARCHS="i386" -DCMAKE_SYSTEM_PROCESSOR=X86 \
-DENABLE_BITCODE=1 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 -DCMAKE_BUILD_TYPE=Release -DDOBBY_DEBUG=OFF -DDOBBY_GENERATE_SHARED=OFF -DGenerateDarwinFramework=OFF

make -j4

# build for x86_64
mkdir $PRODUCT_DIR/build_for_x86_64 && cd $PRODUCT_DIR/build_for_x86_64
cmake ../../ \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DPLATFORM=SIMULATOR64 -DARCHS="x86_64" -DCMAKE_SYSTEM_PROCESSOR=X86_64 \
-DENABLE_BITCODE=1 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 -DCMAKE_BUILD_TYPE=Release -DDOBBY_DEBUG=OFF -DDOBBY_GENERATE_SHARED=OFF -DGenerateDarwinFramework=OFF

make -j4

LIB_DIR=$CURRENT_DIR/lib

rm -rf $LIB_DIR || true
mkdir $LIB_DIR

# 生成static library
cp -R $DOBBY_MASTER_DIR/include $LIB_DIR/include
lipo -create $PRODUCT_DIR/build_for_i386/libdobby.a $PRODUCT_DIR/build_for_x86_64/libdobby.a $PRODUCT_DIR/build_for_armv7/libdobby.a $PRODUCT_DIR/build_for_arm64/libdobby.a -output $LIB_DIR/libdobby.a

# 移除dobby master
rm -rf $DOBBY_MASTER_DIR

open $CURRENT_DIR

```

**Comment by wjiuxing** [comment]
@ko1o 我的还是会报错。 我的电脑 11.2.3，Xcode Version 12.4 (12D4e)， cmake version 3.19.3。

```shell
/Users/x/workspace/github/Dobby/builtin-plugin/SupervisorCallMonitor/system_call_log_handler.cc:29:2: error: "Not Support Architecture."
#error "Not Support Architecture."
 ^
/Users/x/workspace/github/Dobby/builtin-plugin/SupervisorCallMonitor/system_call_log_handler.cc:35:51: error: no member named 'sp' in '_RegisterContext'
  addr_t closure_trampoline_reserved_stack = ctx->sp - sizeof(addr_t);
                                             ~~~  ^
/Users/x/workspace/github/Dobby/builtin-plugin/SupervisorCallMonitor/system_call_log_handler.cc:62:20: error: no member named 'fp' in '_RegisterContext'
  addr_t fp = ctx->fp;
              ~~~  ^
/Users/x/workspace/github/Dobby/builtin-plugin/SupervisorCallMonitor/system_call_log_handler.cc:82:41: error: no member named 'x16' in '_RegisterContext::(anonymous struct at
      /Users/x/workspace/github/Dobby/./include/dobby.h:106:5)'
  int  syscall_rum  = ctx->general.regs.x16;
                      ~~~~~~~~~~~~~~~~~ ^
/Users/x/workspace/github/Dobby/builtin-plugin/SupervisorCallMonitor/system_call_log_handler.cc:89:115: error: no member named 'x0' in '_RegisterContext::(anonymous struct at
      /Users/x/workspace/github/Dobby/./include/dobby.h:106:5)'
      sprintf(buffer, "[svc-%d] %s:%s\n", syscall_rum, syscall_num_to_str(syscall_rum), (char *)ctx->general.regs.x0);
                                                                                                ~~~~~~~~~~~~~~~~~ ^
5 errors generated.
make[2]: *** [builtin-plugin/SupervisorCallMonitor/CMakeFiles/supervisor_call_monitor.dir/system_call_log_handler.cc.o] Error 1
```

**Comment by ko1o** [comment]
@wjiuxing 留个邮箱 我把.a发你一份吧 你先看看能否正常使用

**Comment by wjiuxing** [comment]
@ko1o 非常感谢！ 983556605@qq.com

**Comment by ko1o** [comment]
> @ko1o 非常感谢！ [983556605@qq.com](mailto:983556605@qq.com)

已发送。
