### ISSUE TITLE
是否支持Mac Catalyst

### ISSUE THREAD

**Issue by ko1o** [jmpews/Dobby#123]
看 https://github.com/leetal/ios-cmake 这里已经更新Xcode12.2 build，该库是不是也更新下哈？

**Comment by jmpews** [comment]
现在 Xcode 12.2 会存在编译错误吗？

**Comment by ko1o** [comment]
这里我应该描述错了 主要是需要支持下 Mac Catalyst

**Comment by jmpews** [comment]
> 看 https://github.com/leetal/ios-cmake 这里已经更新 Xcode12.2 build，该库是不是也更新下哈？

no need ios-cmake anymore
