### ISSUE TITLE
 fatal error: './variable_cache.h' file not found

### ISSUE THREAD

**Issue by neobenedict** [jmpews/Dobby#151]
FAILED: dobby/external/misc-helper/CMakeFiles/misc_helper.dir/variable_cache.c.o
C:\Android\android-ndk-r21d\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=armv7-none-linux-androideabi19 --gcc-toolchain=C:/Android/android-ndk-r21d/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Android/android-ndk-r21d/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -I../../lib/dobby/include -I../../lib/dobby/builtin-plugin -I../../lib/dobby/builtin-plugin/SymbolResolver -I../../lib/dobby/external/logging -I../../lib/dobby/source -I../../lib -I../../lib/cocos -I../../lib/CRCpp -I../../lib/utf8-cpp/source -I"C:/Program Files/Unity/Hub/Editor/2018.4.8f1/Editor/Data/il2cpp/libil2cpp" -I../../lib/dobby/external/misc-helper/. -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security  -fomit-frame-pointer -ffunction-sections -fdata-sections -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden -Oz -DNDEBUG  -fvisibility=hidden -fvisibility-inlines-hidden -g0 -O3 -ffunction-sections -fdata-sections -fPIC -std=gnu11 -MD -MT dobby/external/misc-helper/CMakeFiles/misc_helper.dir/variable_cache.c.o -MF dobby\external\misc-helper\CMakeFiles\misc_helper.dir\variable_cache.c.o.d -o dobby/external/misc-helper/CMakeFiles/misc_helper.dir/variable_cache.c.o -c ../../lib/dobby/external/misc-helper/variable_cache.c
../../lib/dobby/external/misc-helper/variable_cache.c:1:10: fatal error: './variable_cache.h' file not found
#include "./variable_cache.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by neobenedict** [comment]
https://github.com/jmpews/Dobby/blob/master/CMakeLists.txt#L331

**Comment by jmpews** [comment]
Fixed
