### ISSUE TITLE
最新的版本在Mac x64上编译错误

### ISSUE THREAD

**Issue by tbruceyu** [jmpews/Dobby#153]
最新的版本在Mac x64上编译错误：
`
/Users/yutao/Projects/Android/Dobby/builtin-plugin/SupervisorCallMonitor/mach_system_call_log_handler.cc:61:5: warning:
      ISO C++11 does not allow conversion from string literal to 'char *'
      [-Wwritable-strings]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/vm_map.h:1430:7: note:
      expanded from macro 'subsystem_to_name_map_vm_map'
    { "mach_make_memory_entry_64", 3825 },\
      ^
/Users/yutao/Projects/Android/Dobby/builtin-plugin/SupervisorCallMonitor/mach_system_call_log_handler.cc:61:5: warning:
      ISO C++11 does not allow conversion from string literal to 'char *'
      [-Wwritable-strings]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/vm_map.h:1431:7: note:
      expanded from macro 'subsystem_to_name_map_vm_map'
    { "vm_map_64", 3826 },\
      ^
/Users/yutao/Projects/Android/Dobby/builtin-plugin/SupervisorCallMonitor/mach_system_call_log_handler.cc:61:5: warning:
      ISO C++11 does not allow conversion from string literal to 'char *'
      [-Wwritable-strings]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/vm_map.h:1432:7: note:
      expanded from macro 'subsystem_to_name_map_vm_map'
    { "vm_purgable_control", 3830 },\
      ^
/Users/yutao/Projects/Android/Dobby/builtin-plugin/SupervisorCallMonitor/mach_system_call_log_handler.cc:61:5: warning:
      ISO C++11 does not allow conversion from string literal to 'char *'
      [-Wwritable-strings]
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/vm_map.h:1433:7: note:
      expanded from macro 'subsystem_to_name_map_vm_map'
    { "vm_map_exec_lockdown", 3831 }
      ^
/Users/yutao/Projects/Android/Dobby/builtin-plugin/SupervisorCallMonitor/mach_system_call_log_handler.cc:126:51: error:
      no member named 'sp' in '_RegisterContext'
  addr_t closure_trampoline_reserved_stack = ctx->sp - sizeof(addr_t);
                                             ~~~  ^
/Users/yutao/Projects/Android/Dobby/builtin-plugin/SupervisorCallMonitor/mach_system_call_log_handler.cc:153:20: error:
      no member named 'fp' in '_RegisterContext'
  addr_t fp = ctx->fp;
              ~~~  ^
/Users/yutao/Projects/Android/Dobby/builtin-plugin/SupervisorCallMonitor/mach_system_call_log_handler.cc:173:39: error:
      no member named 'x16' in '_RegisterContext::(anonymous struct at
      /Users/yutao/Projects/Android/Dobby/./include/dobby.h:118:5)'
  int syscall_rum = ctx->general.regs.x16;
`

**Comment by jmpews** [comment]
不要构建所有 target, `SupervisorCallMonitor` 仅适用于 aarch64
