### ISSUE TITLE
 MacOS 11.4  Xcode 12.5  编译Dobby 时，产生错误

### ISSUE THREAD

**Issue by fuqiangleon** [jmpews/Dobby#154]
需求：希望使用dobby 将App的网络请求通过 hook connect 转发到指定socks5 代理 @jmpews 不知道是否可行，请指点，谢谢。
错误：

/Users/hugo/Downloads/Dobby-master/builtin-plugin/SupervisorCallMonitor/sensitive_api_monitor.cc:16:37: No member named 'x' in '_RegisterContext::(anonymous union at /Users/hugo/Downloads/Dobby-master/include/dobby.h:88:3)'

No member named 'x16' in '_RegisterContext::(anonymous struct at /Users/hugo/Downloads/Dobby-master/include/dobby.h:90:5)'

**Comment by jmpews** [comment]
Fixed

**Comment by fuqiangleon** [comment]
@jmpews  
希望使用dobby 将App的网络请求通过 hook connect 转发到指定socks5 代理  这个需求可以用dobby吗

**Comment by fuqiangleon** [comment]
补充，更新master  最新代码，编译成功，tks
