### ISSUE TITLE
iOS cmake失败CMake Error at CMakeLists.txt:435 (install):   install TARGETS given no FRAMEWORK DESTINATION for shared library FRAMEWORK   target "DobbyX".

### ISSUE THREAD

**Issue by yanyi0** [jmpews/Dobby#158]
-- [Dobby] Enable dynamic binary instrument(hook instruction with register context)
-- [Dobby] Enable near branch trampoline(trampoline within single instruction)
-- [Dobby] Enable global offset table hook
-- [Dobby] Enable symbol resolver
-- [Dobby] Dobby-20210616-bba23cb
-- [Dobby] Generate shared library
CMake Error at CMakeLists.txt:435 (install):
  install TARGETS given no FRAMEWORK DESTINATION for shared library FRAMEWORK
  target "DobbyX".

-- Configuring incomplete, errors occurred!
See also "/Users/xxx/Documents/iOS/Dobby/build_for_ios_arm64/CMakeFiles/CMakeOutput.log".
See also "/Users/xxx/Documents/iOS/Dobby/build_for_ios_arm64/CMakeFiles/CMakeError.log".

**Comment by yanyi0** [comment]
cd Dobby && mkdir build_for_ios_arm64 && cd build_for_ios_arm64

cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake -DPLATFORM=OS64 -DARCHS="arm64" -DCMAKE_SYSTEM_PROCESSOR=arm64 -DENABLE_BITCODE=0 -DENABLE_ARC=0 -DENABLE_VISIBILITY=1 -DDEPLOYMENT_TARGET=9.3 -DDynamicBinaryInstrument=ON -DNearBranch=ON -DPlugin.SymbolResolver=ON -DPlugin.Darwin.HideLibrary=ON -DPlugin.Darwin.ObjectiveC=ON

**Comment by jmpews** [comment]
Fixed (forgot to push
