### ISSUE TITLE
编译动态库cmake怎么链接libdobby.a?

### ISSUE THREAD

**Issue by alienwu2018** [jmpews/Dobby#212]
RT

**Comment by TherCN** [comment]
你用的是android.mk还是cmake
如果是android.mk，在任意地方添加下列代码
`include $(CLEAR_VARS)`
`LOCAL_MODULE         := libdobby`
`LOCAL_SRC_FILES      := 路径/libdobby.a`
`include $(PREBUILT_STATIC_LIBRARY)`
然后在LOCAL_MODULE下添加`LOCAL_STATIC_LIBRARIES := libdobby
`
如图
![Screenshot_2023_0228_134322](https://user-images.githubusercontent.com/85400103/221764638-2a07da72-c3b7-4435-9844-e9bcb7b4ea38.png)

如果是camke，就在`target_link_libraries`下面某行添加
`${CMAKE_CURRENT_SOURCE_DIR}/路径/libdobby.a`
如图
![Screenshot_2023_0228_134146](https://user-images.githubusercontent.com/85400103/221764705-56738d51-fe52-4e79-b7fb-4efb4344819c.png)

**Comment by alienwu2018** [comment]
> 

camke的话，ELF这样是可以的，但是动态库so就不行

**Comment by jmpews** [comment]
try again

**Comment by alienwu2018** [comment]
> try again

好的，感谢回复
