### ISSUE TITLE
macos下无法编译iOS的静态库

### ISSUE THREAD

**Issue by whitebee-maker** [jmpews/Dobby#215]
在mac机器下面用`python3 scripts/platform_builder.py --platform=iphoneos --arch=all`命令无法编译出静态库
报错信息如下:
`cp: /Users/xk/Git/Dobby/build/cmake-build-iphoneos-arm64e/libdobby.a: No such file or directory
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/xk/Git/Dobby/build/iphoneos/arm64/libdobby.a (No such file or directory)
Traceback (most recent call last):
  File "/Users/xk/Git/Dobby/scripts/platform_builder.py", line 240, in <module>
    DarwinPlatformBuilder.lipo_create_fat(project_dir, platform, output_name)
  File "/Users/xk/Git/Dobby/scripts/platform_builder.py", line 173, in lipo_create_fat
    subprocess.run(cmd, check=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['lipo', '-create', '/Users/xk/Git/Dobby/build/iphoneos/arm64/libdobby.a', '/Users/xk/Git/Dobby/build/iphoneos/arm64e/libdobby.a', '-output', '/Users/xk/Git/Dobby/build/iphoneos/libdobby.a']' returned non-zero exit status 1.
`
我需要的就是`libdobby.a`文件，但是它没有生成。

**Comment by whitebee-maker** [comment]
补充:
我用 commit:914110fbdaf875d9863101ab36dea59a0a233fc3 编译是成功的, 但最新的 ed69ebebc762b05c1bbce005f3d470cdb22602b8 就不成功

**Comment by jmpews** [comment]
fixed
