### ISSUE TITLE
-DOBBY_DEBUG = OFF 选项，不起作用，调试日志依然输出！

### ISSUE THREAD

**Issue by HOOKDLL** [jmpews/Dobby#217]
我测试了好几次更新！-DOBBY_DEBUG = OFF 似乎已失去作用！
测试环境：macOS 13 M2 arm64

**Comment by jmpews** [comment]
`-DCMAKE_BUILD_TYPE=Release`

**Comment by HOOKDLL** [comment]
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/39880388/226560445-a6081542-ee74-46a0-ab28-6afb0ae496d3.png">
-DCMAKE_BUILD_TYPE=Release 是有的，生成的库文件还是有调试信息

**Comment by jmpews** [comment]
fixed
