### ISSUE TITLE
BKSDisplayServices assert exception occur when hook objc_msgSend

### ISSUE THREAD

**Issue by everettjf** [jmpews/Dobby#43]
Hi,
I'm using the latest code in master (commit no: f2adeae  ) for AppleTrace.

For reproduct the assert exception in BKSDisplayServices , please follow the 3 steps below: 

1. 
```
git clone git@github.com:everettjf/AppleTrace.git
git checkout crash
```

2. Open `AppleTrace/sample/TraceAllMsgDemo/TraceAllMsgDemo.xcodeproj` 

3. Connect arm64 device, `command+r` run.

Then assert exception occur : ( it is a assert  BKSDisplayServices assert)

```
2018-10-28 17:44:31.651408+0800 TraceAllMsgDemo[21902:2695316] *** Assertion failure in Boolean BKSDisplayServicesStart(void)(), /BuildRoot/Library/Caches/com.apple.xbs/Sources/BackBoardServicesFramework/backboarddaemon-195.45.7/BackBoardServices/BKSDisplayServices.m:48
```

![image](https://user-images.githubusercontent.com/1665109/47614336-6ca04000-dad9-11e8-9e85-c82db6f96ae2.png)

**Comment by kobe1941** [comment]
我也遇到了类似的问题，hook objc_msgSend这个函数的时候，腾讯体育的播放器在播放视频的时候会崩溃（非播放视频的时候不会崩溃，当然log太多会卡住Xcode），SIGBORT。注释掉hook的这一行就没问题，可以继续看视频。

![image](https://user-images.githubusercontent.com/7099017/47844580-b781c680-ddfd-11e8-863c-81b64afcc6a7.png)
