### ISSUE TITLE
iOS 12 codesign reason crash

### ISSUE THREAD

**Issue by jmpews** [jmpews/Dobby#53]
RT.

**Comment by stoneJu** [comment]
这个啥时候会修复呢

**Comment by jmpews** [comment]
已经有方案修复. 但是感觉不是很优雅. 

frida for unc0ver: `https://github.com/frida/frida-gum/blob/815e71cffae5e0d4a79b02cf04c1073382193211/gum/backend-darwin/gumcodesegment-darwin.c#L344`
