### ISSUE TITLE
Linux 4.18 not support 

### ISSUE THREAD

**Issue by yuzehome** [jmpews/Dobby#55]
I can build in Ubuntu18.04 ,but i can't use!

Debug and found ,ZzReplace has someting error!

ZzReplace->route->Dispatch();-> Prepare();->**GenRelocateCode** error at this 

I debug in Ubuntu 14.0,It running.Linux version is 4.4

**Comment by jmpews** [comment]
thx, i will try & fix later. (example code?)

yuzehome <notifications@github.com> 于2019年6月19日周三 下午2:47写道：

**Comment by yuzehome** [comment]
#include <stdio.h>
#include <unistd.h>
#include "hookzz.h"


size_t (*origin_fread)(void * ptr, size_t size, size_t nitems, FILE * stream);
size_t (fake_fread)(void * ptr, size_t size, size_t nitems, FILE * stream) {
    printf("[FileMonitor|fread|model|%p] >>> %ld, %ld\n", ptr, size, nitems);
    return origin_fread(ptr, size, nitems, stream);
}

void hook_fread() 
{
    
    int status = ZzReplace((void *)fread, (void *)fake_fread, (void **)&origin_fread); 
    int a  =10;
}

int main()
{
    hook_fread();
    int t = getpid();
    getppid();
    FILE* file = fopen("/home/pi/1.txt","r");
    char buf[1024] = {0};
    size_t n = fread(buf,4,1,file);
    //fwrite("1234" , 4 , 1 , file);
    fclose(file);
   
    return 0;
}

**Comment by yuzehome** [comment]
this is my test code! on ubuntu14.04
Print error!
[!]  [/home/pi/prj/HookZz-dev/srcxx/InstructionRelocation/x64/X64InstructionRelocation.cc:50:GenRelocateCodeTo]
unimplemented code!!!
[!]  [/home/pi/prj/HookZz-dev/srcxx/InstructionRelocation/x64/X64InstructionRelocation.cc:50:GenRelocateCodeTo]
unimplemented code!!!

**Comment by jmpews** [comment]
fixed
