### ISSUE TITLE
编译失败，提示“ZzInstrument”找不到

### ISSUE THREAD

**Issue by weixingdeng** [jmpews/Dobby#57]
Undefined symbols for architecture arm64:
  "_ZzInstrument", referenced from:
      ____main in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

编译出来的libhookzz.dylib，放IDA里面看也没有ZzInstrument这个方法，麻烦问下是使用的原因吗。。

**Comment by weixingdeng** [comment]
已解决。

**Comment by geekonion** [comment]
> 已解决。

也遇到了这个问题，不知道怎么解决，求指点。

**Comment by weixingdeng** [comment]
> > 已解决。
> 
> 也遇到了这个问题，不知道怎么解决，求指点。

Make文件里面有开关，打开重新生成好像就可以了

**Comment by geekonion** [comment]
@weixingdeng 谢谢。

**Comment by stoneJu** [comment]
> > > 已解决。
> > 
> > 
> > 也遇到了这个问题，不知道怎么解决，求指点。
> 
> Make文件里面有开关，打开重新生成好像就可以了

求助，我还是没找到是哪个开关

**Comment by stoneJu** [comment]
> > > 已解决。
> > 
> > 
> > 也遇到了这个问题，不知道怎么解决，求指点。
> 
> Make文件里面有开关，打开重新生成好像就可以了

找到了
