### ISSUE TITLE
iOS 11/12越狱环境下崩溃badSignature

### ISSUE THREAD

**Issue by lich4** [jmpews/Dobby#77]
iOS 11/12越狱环境下崩溃badSignature

使用DobbyInstrument对指令进行hook后崩溃

Dec 31 01:38:14 T002 assertiond[1945] <Notice>: [com.test.test:6826] Got exit context: <BKSProcessExitContext: 0x100431d60; reason: badSignature>
Dec 31 01:38:14 T002 SpringBoard[6784] <Notice>: Process exited: <FBApplicationProcess: 0x109da6430; com.test.test (com.test.test); pid: -1> -> <FBApplicationProcessExitContext: 0x1c0a56e00; exitReason: badSignature; terminationReason: (none)> {
    stateAtExit = <FBProcessState:  0x1c0c3cfa0; pid: 6826; taskState: Not Running; visibility: Background>;
}

**Comment by jmpews** [comment]
#53 

是 unc0ver 的 jailbreak 吧? 

已经在处理, 估计明天可以放出来.

**Comment by lich4** [comment]
太牛了，大佬
