### ISSUE TITLE
DobbyWrap 符号找不到

### ISSUE THREAD

**Issue by LZRight123** [jmpews/Dobby#80]
int DobbyHook(void *function_address, void *replace_call, void **origin_call);
DobbyHook函数可以正常使用，但是在使用 DobbyWrap 函数时报错:
Undefined symbols for architecture arm64:
  "_DobbyWrap", referenced from:

顺便问下，我用 build_fat_dylib.sh跑出来 的是 framework 是新版本改成了这样的吗

**Comment by jmpews** [comment]
DobbyWrap removed, use DobbyInstrument
