### ISSUE TITLE
arm32位error

### ISSUE THREAD

**Issue by liumengdeqq** [jmpews/Dobby#85]
/Dobbyt/Dobby/source/InterceptRoutingTrampoline/arm/trampoline-arm.cc:17:10: error: 
      cannot initialize return object of type 'CodeBuffer *' with an rvalue of
      type 'CodeBufferBase *'
  return turbo_assembler_.GetCodeBuffer()->copy();
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dobbyt/Dobby/source/InterceptRoutingTrampoline/arm/trampoline-arm.cc:34:10: error: 
      cannot initialize return object of type 'CodeBuffer *' with an rvalue of
      type 'CodeBufferBase *'
  return thumb_turbo_assembler_.GetCodeBuffer()->copy()

**Comment by maxli77** [comment]
我也是报这个错误，我的解决方法是把返回值强制转换 成  (CodeBuffer *) 就可以正常编译了

**Comment by jmpews** [comment]
fixed
