### ISSUE TITLE
iOS调试可以hook,但是直接真机运行就崩溃

### ISSUE THREAD

**Issue by fero2004** [jmpews/Dobby#91]
用编译出来的framework是这个问题,然后源码直接集成也是这个问题

Exception Type:  EXC_CRASH (SIGKILL - CODESIGNING)
Exception Codes: 0x0000000000000001, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace CODESIGNING, Code 0x2
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x00000001acc98784 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001acc97ba8 mach_msg + 76
2   libsystem_kernel.dylib        	0x00000001accb77b0 vm_copy + 104
3   libFifaDylib.dylib            	0x00000001065d5ad4 0x1065ac000 + 170708
4   libFifaDylib.dylib            	0x00000001065b65b4 0x1065ac000 + 42420
5   libFifaDylib.dylib            	0x00000001065d0a00 0x1065ac000 + 150016
6   libFifaDylib.dylib            	0x00000001065c00b0 0x1065ac000 + 82096
7   libFifaDylib.dylib            	0x00000001065c26dc 0x1065ac000 + 91868
8   libFifaDylib.dylib            	0x00000001065c2668 0x1065ac000 + 91752
9   libFifaDylib.dylib            	0x00000001065c24c8 0x1065ac000 + 91336
10  libFifaDylib.dylib            	0x00000001065d5dac 0x1065ac000 + 171436
11  libdyld.dylib                 	0x00000001accd474c invocation function for block in dyld3::AllImages::runAllInitializersInImage+ 67404 (dyld3::closure::Image const*, dyld3::MachOLoaded const*) + 148
12  libdyld.dylib                 	0x00000001accc63e4 dyld3::closure::Image::forEachInitializer(void const*, void + 9188 (void const*) block_pointer) const + 104
13  libdyld.dylib                 	0x00000001accd4584 invocation function for block in dyld3::AllImages::runInitialzersBottomUp+ 66948 (dyld3::closure::Image const*) + 312

**Comment by jmpews** [comment]
Jailbreak needed

https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html
