### ISSUE TITLE
集成Hook ObjectC 函数的接口是哪一个

### ISSUE THREAD

**Issue by zupu8** [jmpews/Dobby#99]
大佬，Dobby集成Hook ObjectC 函数的接口是哪一个，目前只看到了针C C++函数的Hook接口（DobbyHook），不知道还有没有封装针对OCHook的接口？

**Comment by jmpews** [comment]
https://github.com/jmpews/Dobby/blob/master/builtin-plugin/ObjectiveC/objective_c_tookit.mm
